# AUTOGENERATED! DO NOT EDIT! File to edit: test_streamlit.ipynb.

# %% auto 0
__all__ = []

# %% test_streamlit.ipynb 3
pip install streamlit_jupyter

# %% test_streamlit.ipynb 4
from datetime import datetime

import streamlit as st

# from streamlit_jupyter import StreamlitPatcher, tqdm

# %% test_streamlit.ipynb 6
st.title("Example")

# %% test_streamlit.ipynb 7
st.markdown(
    """

This is a test page demonstrating the use of `streamlit_jupyter`.

If you're seeing this in jupyter, then it's working!

"""
)
