# AUTOGENERATED! DO NOT EDIT! File to edit: web_app.ipynb.

# %% auto 0
__all__ = []

# %% web_app.ipynb 7
import pandas as pd
import streamlit as st

# Setup file upload
global df
uploaded_file = st.sidebar.file_uploader(label="Upload your Excel file", type = ['csv','xlsx'])
if uploaded_file is not None:
    df = pd.read_csv(uploaded_file, encoding='utf-8', sep=';')
    st.write(df)
    st.dataframe(df,3000,500)

file = 'C:/Users/Kévin/Downloads/OPENCLASSROOM/P10/dataframe_final_20230529.csv'

df_final = pd.read_csv(file, encoding='utf-8', sep=';')

st.write(df)
