# AUTOGENERATED! DO NOT EDIT! File to edit: web_app.ipynb.

# %% auto 0
__all__ = []

# %% web_app.ipynb 5
import pandas as pd
import streamlit as st
from datetime import datetime


st.title("Détection de faux billets 💵")
st.markdown(
    """

Bienvenue dans l'application web simplifiée de détection de faux billets.

Cette application aide à prédire si un billet sera faux ou vrai selon ses caractéristiques.
Veuillez svp faire votre sélection au sein des variables en side-bar pour obtenir votre résultat.

"""
)

uploaded_file = st.sidebar.file_uploader(label="Upload your Excel file", type = ['csv'])
if uploaded_file is not None:
    df = pd.read_csv(uploaded_file, encoding='utf-8', sep=';')

else:
    st.title("⚠️ Attention, veuillez déposer un fichier")

st.sidebar.header("Les paramètres du billet à l'étude")

def user_input():

    diagonal = st.sidebar.selectbox('la diagonale du billet', options=df['diagonal'].values, index=0)
    height_left = st.sidebar.selectbox('la hauteur gauche du billet', options=df['height_left'].values, index=0)
    height_right = st.sidebar.selectbox('la hauteur droite du billet', options=df['height_right'].values, index=0)
    margin_low = st.sidebar.selectbox('la marge basse du billet', options=df['margin_low'].values, index=0)
    margin_up = st.sidebar.selectbox('la marge haute du billet', options=df['margin_up'].values, index=0)
    length = st.sidebar.selectbox('la longueur du billet', options=df['length'].values, index=0)
    
    data={
        'diagonal':diagonal,
        'height_left': height_left,
        'height_right': height_right,
        'margin_low': margin_low,
        'margin_up': margin_up,
        'length': length
    }
    
    billet_parametres=pd.DataFrame(data, index=[0])
    
    return billet_parametres

df_=user_input()

st.subheader('On veut trouver si notre billet (avec les caractéristiques suivantes) est vrai ou faux')
st.write(df_.iloc[:,0:6])


st.subheader('La prédiction du billet est:')
st.write(df.iloc[:,7:10])
st.write(df.iloc[:,7:10] & df.loc['diagonal']==df_.loc['diagonal'] & df.loc['height_left']==df_.loc['height_left']
        & df.loc['height_right']==df_.loc['height_right'] & df.loc['margin_low']==df_.loc['margin_low']
        & df.loc['margin_up']==df_.loc['margin_up'] & df.loc['length']==df_.loc['length'])
