# AUTOGENERATED! DO NOT EDIT! File to edit: web_app_V2.ipynb.

# %% auto 0
__all__ = []

# %% web_app_V2.ipynb 5
import pandas as pd
import numpy as np
import streamlit as st
from datetime import datetime
import json
import joblib
from sklearn.preprocessing import StandardScaler


st.title("Détection de faux billets 💵")
st.markdown(
    """

Bienvenue dans l'application web simplifiée de détection de faux billets.

Cette application aide à prédire si un billet sera faux ou vrai selon ses caractéristiques.
Veuillez svp déposer le fichier CSV et le modèle JSON avant de pouvoir faire votre sélection au sein des variables en side-bar pour obtenir votre résultat.

"""
)

uploaded_file = st.sidebar.file_uploader(label="Déposez le fichier CSV 'dataframe_final' ici", type = ['csv'])
if uploaded_file is not None:
    df = pd.read_csv(uploaded_file, encoding='utf-8', sep=';')

else:
    st.title("⚠️ Attention, veuillez déposer un fichier")

uploaded_model = st.sidebar.file_uploader(label="Déposez le fichier JSON 'model_trained' ici")
if uploaded_model is not None:
    regression = joblib.load(uploaded_model)
    
else:
    st.title("⚠️ Attention, veuillez déposer un modèle")

    
st.sidebar.header("Les paramètres du billet à l'étude")

def user_input():
    
    diagonal = st.sidebar.slider('Diagonale du billet', 171.04, 173.01, 171.04)
    height_left = st.sidebar.slider('Hauteur gauche du billet', 103.14, 104.88, 103.14)
    height_right = st.sidebar.slider('Hauteur droite du billet', 102.82, 104.95, 102.82)
    margin_low = st.sidebar.slider('Marge basse du billet', 2.98, 6.90, 2.98)
    margin_up = st.sidebar.slider('Marge haute du billet', 2.27, 3.91, 2.27)
    length = st.sidebar.slider('Longueur du billet', 109.49, 114.44, 109.49)
    
    data={
        'diagonal':diagonal,
        'height_left': height_left,
        'height_right': height_right,
        'margin_low': margin_low,
        'margin_up': margin_up,
        'length': length
    }
    
    billet_parametres=pd.DataFrame(data, index=[0])
    
    return billet_parametres

df_ = user_input()


st.subheader('On veut trouver si notre billet (avec les caractéristiques suivantes) est vrai ou faux')
st.write(df_.iloc[:,0:6])
st.write(df_)

#Standardisation des valeurs
# X_csv = df_.drop(['id'], axis=1)
scaler = StandardScaler()
scaler.fit(df.drop(['id'], axis=1))
X_csv_scaled = scaler.transform(df_)
X_csv_std = pd.DataFrame(X_csv_scaled, columns=df.columns)
st.write(X_csv_scaled)
st.write(X_csv_std)

# # Regression logistique avec le modèle déjà entraîné (scikit-learn) du fichier pickle
# y_log = regression.predict(X_csv_std)
# predictions = []
# for i in range(0, len(y_log)):
#     predictions.append(y_log[i])

# predictions = pd.concat([
#     pd.DataFrame(
#     [predictions]).rename(index={0: 'Prédiction'}).T.replace(
#     {False: 'Faux billet', True: 'Vrai billet'}),
#     pd.DataFrame(
#     regression.predict_proba(X_csv_std)).rename(
#     columns={0: 'Probabilité de faux', 1: 'Probabilité de vrai'})], axis=1)
# # predictions['id'] = dataframe['id'].unique()

# st.subheader('La prédiction du billet est:')
# st.write(predictions)

# Prédiction avec le modèle
y_pred = regression.predict(X_csv_std)
predictions = pd.DataFrame(y_pred, columns=['Prédiction'])
predictions['Prédiction'] = predictions['Prédiction'].replace({False: 'Faux billet', True: 'Vrai billet'})
predictions['Probabilité de faux'] = regression.predict_proba(X_csv_std)[:, 0]
predictions['Probabilité de vrai'] = regression.predict_proba(X_csv_std)[:, 1]

st.subheader('La prédiction du billet est:')
st.write(predictions)
